DEFAULT_PAGE_SIZE = 6
AVATAR_MAX_SIZE_MB = 5
AVATAR_MAX_SIZE_BYTES = AVATAR_MAX_SIZE_MB * 1024 * 1024
AVATAR_TOO_LARGE_MESSAGE = (
    'Размер файла не должен превышать '
    f'{AVATAR_MAX_SIZE_MB} МБ'
)
AVATAR_ALLOWED_FORMATS = {'JPEG', 'JPG', 'PNG'}
AVATAR_INVALID_IMAGE_MESSAGE = 'Не удалось прочитать изображение'
AVATAR_INVALID_FORMAT_MESSAGE = (
    'Допустимы только изображения формата JPG или PNG'
)

__all__ = [
    'DEFAULT_PAGE_SIZE',
    'AVATAR_MAX_SIZE_MB',
    'AVATAR_MAX_SIZE_BYTES',
    'AVATAR_TOO_LARGE_MESSAGE',
    'AVATAR_ALLOWED_FORMATS',
    'AVATAR_INVALID_IMAGE_MESSAGE',
    'AVATAR_INVALID_FORMAT_MESSAGE',
]
