volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -h 127.0.0.1 -p "${POSTGRES_PORT:-5432}" -U "${POSTGRES_USER:-postgres}" -d "${POSTGRES_DB:-${POSTGRES_USER:-postgres}}"' ]
      start_period: 60s
      interval: 10s
      timeout: 5s
      retries: 12

  backend:
    image: mortifertis/foodgram_backend:latest
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static:/app/static
      - media:/app/media
      - ./data:/app/data:ro
    restart: unless-stopped

  frontend:
    image: mortifertis/foodgram_frontend:latest
    env_file: .env
    volumes:
      - static:/static
    depends_on:
      - backend
    restart: "no"

  gateway:
    image: mortifertis/foodgram_gateway:latest
    env_file: .env
    ports:
      - "10000:80"
    volumes:
      - static:/static
      - media:/media
      - ./nginx/gateway.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    restart: unless-stopped
