version: "3.8"

services:
  db:
    image: postgres:13.10
    container_name: foodgram-db
    restart: always
    env_file:
      - .env.backend
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foodgram-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.backend
    environment:
      DJANGO_SETTINGS_MODULE: foodgram_backend.settings
      DB_ENGINE: django.db.backends.postgresql
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "10000:8000"
    volumes:
      - media_value:/app/media
      - static_value:/app/collected_static

volumes:
  pg_data:
  media_value:
  static_value:
