TAG_NAME_MAX_LENGTH = 200
TAG_COLOR_MAX_LENGTH = 7
TAG_SLUG_MAX_LENGTH = 200

INGREDIENT_NAME_MAX_LENGTH = 200
INGREDIENT_MEASUREMENT_MAX_LENGTH = 200

RECIPE_NAME_MAX_LENGTH = 200
RECIPE_COOKING_TIME_MIN = 1
RECIPE_COOKING_TIME_MIN_MESSAGE = (
    'Минимальное время приготовления — '
    f'{RECIPE_COOKING_TIME_MIN} минута'
)
RECIPE_IMAGE_UPLOAD_DIR = 'recipes/'
RECIPE_SHORT_LINK_MAX_LENGTH = 32
RECIPE_SHORT_LINK_LENGTH = 6
RECIPE_SHORT_LINK_ALLOWED_CHARS = (
    'abcdefghijklmnopqrstuvwxyz'
    'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    '0123456789'
)

RECIPE_INGREDIENT_AMOUNT_MIN = 1
RECIPE_INGREDIENT_AMOUNT_MESSAGE = (
    'Количество должно быть не меньше '
    f'{RECIPE_INGREDIENT_AMOUNT_MIN}'
)
