services:
  db:
    image: postgres:13.10
    env_file:
      - .env.backend
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -h 127.0.0.1 -p "${POSTGRES_PORT:-5432}" -U "${POSTGRES_USER:-postgres}" -d "${POSTGRES_DB:-${POSTGRES_USER:-postgres}}"' ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 20s

  backend:
    image: mortifertis/foodgram_backend:latest
    container_name: foodgram-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_ENGINE: django.db.backends.postgresql
    volumes:
      - media_value:/app/media
      - static_value:/app/collected_static

  nginx:
    image: nginx:1.25.4-alpine
    container_name: foodgram-nginx
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - static_value:/usr/share/nginx/html/static/
      - media_value:/usr/share/nginx/html/media/

volumes:
  pg_data:
  media_value:
  static_value: