server {
  listen 80;
  index index.html;

  client_max_body_size 20M;
  server_tokens off;

  location /static/ {
    alias /static/;
    access_log off;
    expires 7d;
  }

  location /media/ {
    alias /media/;
    access_log off;
    expires 7d;
  }

  location /api/ {
    proxy_pass http://backend:8000$request_uri;
    proxy_redirect off;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /admin/ {
    proxy_pass http://backend:8000$request_uri;
    proxy_redirect off;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location / {
    alias /static/;
    try_files $uri $uri/ /index.html;
  }

  location /healthz {
    return 200 'ok';
    add_header Content-Type text/plain;
  }
}
