# Generated by Django 4.2.11 on 2025-10-17 14:05

from django.db import migrations, models
from django.utils.crypto import get_random_string


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    def _generate_unique_short_link(model, length=6):
        allowed_chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
        while True:
            candidate = get_random_string(length=length, allowed_chars=allowed_chars)
            if not model.objects.filter(short_link=candidate).exists():
                return candidate

    def _populate_short_links(apps, schema_editor):
        Recipe = apps.get_model("recipes", "Recipe")
        empty_value_filter = models.Q(short_link="") | models.Q(short_link__isnull=True)
        for recipe in Recipe.objects.filter(empty_value_filter):
            recipe.short_link = _generate_unique_short_link(Recipe)
            recipe.save(update_fields=["short_link"])

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="short_link",
            field=models.SlugField(
                blank=True, max_length=32, unique=True, verbose_name="Короткая ссылка"
            ),
        ),
        migrations.RunPython(_populate_short_links, migrations.RunPython.noop),
    ]
