# Generated by Django 4.2.11 on 2025-10-25 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_subscription_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("id",),
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="Аватар"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[
                    django.core.validators.EmailValidator(),
                    django.core.validators.MaxLengthValidator(254),
                ],
                verbose_name="Адрес электронной почты",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Обязательное поле. Не более 150 символов. Только буквы, цифры и @/./+/-/_",
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Введите корректное имя пользователя. Допустимы только буквы, цифры и знаки @/./+/-/_.",
                        regex="^[\\w.@+-]+\\Z",
                    ),
                    django.core.validators.MaxLengthValidator(150),
                ],
                verbose_name="Имя пользователя",
            ),
        ),
    ]
